### PR TITLE
wiznet_addons

### PR DESCRIPTION
**Pull request by MaBecker**
add changelog line
remove jsiConsolePrintf for RELEASE=1

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks!

**Comment by MaBecker** [comment]
Can you please update the Espruino Reference page, to make the Wiznet add ons visible.

**Comment by gfwilliams** [comment]
Which add-ons specifically? This PR didn't seem to add anything.

I update the Reference every major release, the idea is if you download an official release then the docs match it, so you're not seeing stuff that isn't available.

Hopefully I'll get a new release out soon though

**Comment by MaBecker** [comment]
> Which add-ons specifically? 

they are spread over multiple pr's #1870, #1871, #1874

> I update the Reference every major release,

perfect, didn't know that, that's really the best time to update it!

**Comment by gfwilliams** [comment]
Ok, great!

**Pull request merged**
