### PR TITLE
Add Sparkfun nRF52832 breakout board

### PR DESCRIPTION
**Pull request by urish**
Link: https://www.sparkfun.com/products/13990

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks, but I'm afraid I'm not merging other company's boards in to the Espruino repo at the moment unless they pay for support - after the initial commit, maintenance pretty much always falls down to me and it's been a nightmare trying to change anything in the build with over 50 different board files.

If Sparkfun themselves are interested I can produce builds and keep boards in the repo for a monthly charge though.

I'll keep this open (there are some other board support PRs open at the moment too) as I'm planning to create a separate branch to stick all these in so they're still easy to get at.

**Comment by urish** [comment]
Sounds fair, let's see if they are game

**Comment by urish** [comment]
https://twitter.com/UriShaked/status/1014186687919017984

**Comment by urish** [comment]
@ShawnHymel @jimblom

**Comment by yerpj** [comment]
@urish : Did you managed to compile Espruino for the SparkFun nRF52832 Breakout?
I gave it a try, but it seems that the device is discoverable only a few seconds after power up, and it is impossible to connect to it. Which Espruino revision did you compile for this Breakout board?

**Comment by urish** [comment]
You can find the code that worked for me in the following branch: https://github.com/urish/Espruino/tree/nrf52832_sparkfun

**Comment by gfwilliams** [comment]
I have now merged this into [`UNMAINTAINED_BOARDS`](https://github.com/espruino/Espruino/tree/UNMAINTAINED_BOARDS)

**Comment by urish** [comment]
Thanks Gordon!

**Pull request closed without merging**
