### PR TITLE
add SDCard support for ESP32

### PR DESCRIPTION
**Pull request by MaBecker**
by removing FLASHFS

### CODE REVIEW

**Comment by MaBecker** [comment]
added pr https://github.com/espruino/Espruino/issues/1779

**Comment by gfwilliams** [comment]
FlashFS was there for a reason (to provide easy access to on-chip flash). I'm not sure it should just be removed?

@wilberforce was the one that added it AFAIK.

**Comment by MaBecker** [comment]
Just checked, ESP32 is the one and only that is using FlashFS.

> FlashFS was there for a reason (to provide easy access to on-chip flash). I'm not sure it should just be removed?

Can you please lookup the download stat for ESP32. 

Personally I am a big fan of the Storage lib and try to avoid SDCards where ever it is possible.

There are only very little section added as flash 8k and 64k

https://github.com/espruino/Espruino/blob/e568c6c7ac78e81b4ab40bb28bd92e8052f4e7b6/targets/esp32/jshardware.c#L733-L742

Ups   0x2B0000 has to be changed to 0x310000

**Comment by MaBecker** [comment]
just added https://github.com/espruino/Espruino/pull/1781

**Comment by wilberforce** [comment]
I don't understand why removing this is an improvement to the ESP32 implementation.

All chips have 4MB or more of memory, and 1Mb had been reserved at work as FlashFS.

Why would you remove this to use an external SD card that only some of the boards have?

Worst case - make it switchable to use either - I just don't see what the benefit is here?

**Comment by MaBecker** [comment]
Thanks for your input. Will check if both can be used.

**Comment by gfwilliams** [comment]
Another option is now `Storage` is better, to extend the flash area used for that and remove FlashFS.

**Comment by MaBecker** [comment]
Using both at the same time cause a undefined reference  to `sdSPISetup`

```
libs/filesystem/jswrap_file.o:(.literal.jswrap_file_kill+0x0): undefined reference to `sdSPISetup'
libs/filesystem/jswrap_file.o: In function `jswrap_file_kill':
/Espruino/repos/MaBecker/libs/filesystem/jswrap_file.c:214: undefined reference to `sdSPISetup'
libs/filesystem/jswrap_file.o: In function `jswrap_E_connectSDCard':
/Espruino/repos/MaBecker/libs/filesystem/jswrap_file.c:155: undefined reference to `sdSPISetup'
collect2: error: ld returned 1 exit status
```

**Comment by MaBecker** [comment]
Not sure how to continue.

Fact :  Adding FLASHFS has broken SDCard function.

Suggestion: Remove FLASHFS for now and bring it back when someone has fixed the linker issue.

OR: Close this and remove SDCard support form ESP32 docs.

**Comment by MaBecker** [comment]
Any hints how to handle the conflict named above?

**Comment by gfwilliams** [comment]
I guess I feel a little like given how much flash there is available, having the filesystem built in is probably more useful than SD card support? I haven't seen too many ESPxx boards with SD cards on? Maybe just the ESP32CAM ones?

I think probably just update the docs to say it's not supported? I don't think you can easily have them coexist since FlashFS uses a 4k block size but SD cards will only want 512

**Comment by MaBecker** [comment]
So let's close this.

**Pull request closed without merging**
