### PR TITLE
New target: Zeisig Gemacht - initial port

### PR DESCRIPTION
**Pull request by ramangopalan**
Firstly, many thanks for Espruino! I now have Espruino running on my
Zeisig Gemacht target. I am able to play with pins and perform I/O on
the SD card. So far so good. Can you please merge this?

### CODE REVIEW

**Comment by jumjum123** [comment]
Hello ramangopalan, is there any information about **_Zeisig gemacht_** or **_Raman's 4 kilowatt toy_**
**_Zeisig gemacht_** sounds german (?)

**Comment by ThomasChr** [comment]
@jumjum123 
Indeed, it sounds german, but it's not really german.
"Zeisig" is a bird and "gemacht" means "done".
So in German this makes no sense...

**Comment by gfwilliams** [comment]
Thanks! Is this something that's available for others to get? Do you have a URL?

I'm afraid it's just not sensible for me to merge things for personal projects - I'd just have hundreds of extra files which would be really confusing. Personally I'd just keep this in your own GitHub, and then you can easily merge any new Espruino commits on top of your changes.

**Comment by ramangopalan** [comment]
> Thanks! Is this something that's available for others to get? Do you
> have a URL?

So sorry. These processor boards are used for control in cryostat
machines. Work aside, I use these boards to teach. Students use these
boards too. Just that they aren't available for sale.

> I'm afraid it's just not sensible for me to merge things for
> personal projects - I'd just have hundreds of extra files which
> would be really

A merge will make things easier but if you can't make an exception, I
will understand. Thanks Gordon!

**Comment by gfwilliams** [comment]
I have now merged this into [`UNMAINTAINED_BOARDS`](https://github.com/espruino/Espruino/tree/UNMAINTAINED_BOARDS)

**Pull request closed without merging**
