### PR TITLE
wiznet_addons

### PR DESCRIPTION
**Pull request by MaBecker**
* setHostname()
* getHostname()
* getStatus()

### CODE REVIEW

**Comment by MaBecker** [comment]
#1806

**Comment by gfwilliams** [comment]
This looks great - thanks!

**Comment by MaBecker** [comment]
Can't find the new function in the new function in http://www.espruino.com/Reference#WIZnet, 
is there something missing in JSON{}?

**Comment by gfwilliams** [comment]
You'd declared them to be part of `Ethernet` which I think is the right class anyway. They seem to be there just fine:  http://www.espruino.com/Reference#Ethernet

**Comment by MaBecker** [comment]
Thanks for checking

**Pull request merged**
