### PR TITLE
cleanup and fixes(fix #752 #1297)

### LINKED ISSUE #752: esp8266 wifi getStatus doesn't show savedMode
Currently savedMode is just a constant, need to show real saved opmode.

### PR DESCRIPTION
**Pull request by MaBecker**
Hi Gordon no sure about this because of so many `Merge remote-tracking branch 'espruino/master'`

If not just give a hint howto do it correct and delete this request Thanks

### CODE REVIEW

**Comment by MaBecker** [comment]
Hmm, 

travis build for  ESP8266_4MB ended with errro:

    ../ld/eagle.rom.addr.v6.ld: No such file or directory

This is included with last line in eagle.app.v6.new.2048.ld.

**Comment by MaBecker** [comment]
No idea how to get rid of this warning:
````
libs/network/esp8266/network_esp8266.c: In function 'esp8266_dumpSocketData':
libs/network/esp8266/network_esp8266.c:203:9: warning: variable 'stateMsg' set but not used [-Wunused-but-set-variable]
   char *stateMsg;
         ^
libs/network/esp8266/network_esp8266.c:187:9: warning: variable 'creationTypeMsg' set but not used [-Wunused-but-set-variable]
   char *creationTypeMsg;
         ^
````

**Comment by gfwilliams** [comment]
I wouldn't worry too much about those warnings.

Assuming you're happy with it, this looks good to merge.

**Comment by MaBecker** [comment]
Ok, what about the travis build error?

**Comment by gfwilliams** [comment]
Not sure what happened, but it works here (and I can't see why your changes would have caused an error) - so I'll merge and see if the next travis build fails :)

**Comment by MaBecker** [comment]
Forgot to mention: It works on my side too

**Comment by gfwilliams** [comment]
It's just rebuilt and it is fine - so must have been a Travis error

**Pull request merged**
