### PR TITLE
ESP8266: switch to SDK 2.2.1 (fix #1207)

### LINKED ISSUE #1207: ESP8266 NONOS SDK  2.1/2.2/2.2.1
As version 2.1 is now available since  May 2017 let give it a try :)

Overview:
* [release info](https://github.com/espressif/ESP8266_NONOS_SDK/releases/tag/v2.1.0)
* [download](https://github.com/espressif/ESP8266_NONOS_SDK/archive/v2.1.0.zip)

Code changes:
* [make/family/ESP8266.make](https://github.com/MaBecker/Espruino/blob/master/make/family/ESP8266.make#L76-L80) 
* [targets/esp8266/espmissingincludes.h](https://github.com/MaBecker/Espruino/blob/master/targets/esp8266/espmissingincludes.h#L61-L82)

Used libraries: NET, TELNET, GRAPHICS,  CRYPTO and NEOPIXEL

make statement

* RELEASE=1 ESPSDK_2_1=1 make

The result looks promising, freeHeap: 11264 

     _____                 _
    |   __|___ ___ ___ _ _|_|___ ___
    |   __|_ -| . |  _| | | |   | . |
    |_____|___|  _|_| |___|_|_|_|___|
              |_| http://espruino.com
     1v93.3119 Copyright 2016 G.Williams 
    Espruino is Open Source. Our work is supported
    only by sales of official boards and donations:
    http://espruino.com/Donate
    Flash map 4MB:1024/1024, manuf 0xe0 chip 0x4016

    >require('ESP8266').logDebug(false);
    =undefined
    >require("ESP8266").getState(); 
    ={
      "sdkVersion": "2.1.0(116b762)",
      "cpuFrequency": 160, "freeHeap": 11264, "maxCon": 10,
      "flashMap": "4MB:1024/1024",
      "flashKB": 4096,
      "flashChip": "0xe0 0x4016"
    }
    >process.env
    ={
      "VERSION": "1v93.3120",
      "BUILD_DATE": "Jul 30 2017",
      "BUILD_TIME": "11:04:34",
      "GIT_COMMIT": "ed27629121172c7c090cae3a6273feb6227d48ef",
      "BOARD": "ESP8266_4MB",
      "CHIP": "ESP8266",
      "CHIP_FAMILY": "ESP8266",
      "FLASH": 0, "RAM": 81920,
      "SERIAL": "5ccf7fc1-120b",
      "CONSOLE": "Serial1",
      "EXPORTS": { "jsvLock": 1075851304, "jsvLockAgainSafe": 1075851356, "jsvUnLock": 1075851728, "jsvSkipName": 1075860364,
        "jsvMathsOp": 1075865696, "jsvMathsOpSkipNames": 1075867412, "jsvNewFromFloat": 1075858076, "jsvNewFromInteger": 1075857976, "jsvNewFromString": 1075857620,
        "jsvNewFromBool": 1075858044, "jsvGetFloat": 1075863436, "jsvGetInteger": 1075859860, 
        "jsvGetBool": 1075863796, "jspeiFindInScopes": 1075879024,
        "jspReplaceWith": 1075878744, "jspeFunctionCall": 1075889112, "jspGetNamedVariable": 1075880868, "jspGetNamedField": 1075881312, "jspGetVarNamedField": 1075881444,
        "jsvNewWithFlags": 1075857344 }
     }
    >

### PR DESCRIPTION
**Pull request by MaBecker**

### CODE REVIEW

**Comment by MaBecker** [comment]
Ups, travis build  failed for ESP8266 ... looks like as not taking the new SDK version

**Comment by wilberforce** [comment]
Here is your error:

https://travis-ci.org/espruino/Espruino/jobs/442342442#L491

**Comment by MaBecker** [comment]
Wow - Yes I can see that error too, but that make no sense ... 

https://github.com/espruino/Espruino/blob/master/libs/network/esp8266/network_esp8266.c#L401-L424

scanning for pvPortFree finds only one position on my side

```
/Volumes/Espruino/repos/Espruino/targets/esp8266/espmissingincludes.h:
   59  
   60  void *vPortMalloc(size_t xWantedSize);
   61: void  pvPortFree(void *ptr);
   62  
   63  uint32 system_get_time();
```

**Comment by MaBecker** [comment]
switched to `Raw Log` and found the reason:
```
travis_fold:start:before_script.1
[0Ktravis_time:start:0ef8fe21
[0K$ source ./scripts/provision.sh $BOARD
ESP8266
ESP8266_NONOS_SDK-2.2.1
xz: (stdin): File format not recognized
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
curl: (23) Failed writing body (0 != 2759)
```

**Comment by wilberforce** [comment]
in a linux shell this fails:

```
curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp8266/ESP8266_NONOS_SDK-2.2.1.tgz| tar Jxf - --no-same-owner                 xz: (stdin): File format not recognized                                                                                                                             tar: Child died with signal 13                                                                                                                                      tar: Error is not recoverable: exiting now           
```

a .tgz  is a gzipped tar file - how did you make the file?

Is it compressed?

**Comment by MaBecker** [comment]
tar -cvzf ESP8266_NONOS_SDK-2.2.1.tgz ESP8266_NONOS_SDK-2.2.1

**Comment by MaBecker** [comment]
curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp8266/ESP8266_NONOS_SDK-2.2.1.tgz| tar Jxf - --no-same-owner 

works fine on Mac OS X

**Comment by MaBecker** [comment]
@wilberforce can you handle the new uploaded file called ESP8266_NONOS_SDK-2.2.1.tar.gz ?

curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp8266/ESP8266_NONOS_SDK-2.2.1.tar.gz| tar Jzf - --no-same-owner

**Comment by MaBecker** [comment]
sorry typo, must be `tar Jxf` correct the last comment

**Comment by wilberforce** [comment]
```
curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp8266/ESP8266_NONOS_SDK-2.2.1.tar.gz| tar Jzf - --no-same-owner

tar: Conflicting compression options

Try 'tar --help' or 'tar --usage' for more information.

```

Are you running tar and then gz ? I think you need to use tar to build the compressed file

**Comment by wilberforce** [comment]
That still fails.

This is how I make it for ESP32:

```
tar cfz ../../deploy/esp-idf.tgz  `find ../esp-idf/components/ -name *.h` \
		`find ../esp-idf/components/ -name *.a` \
		`find ../esp-idf/components/ -name *.ld` \
		`find ../esp-idf/components/esptool_py/esptool/esptool.py`
```

**Comment by MaBecker** [comment]
used two steps 

tar -cvf ESP8266_NONOS_SDK-2.2.1.tar ESP8266_NONOS_SDK-2.2.1

gzip ESP8266_NONOS_SDK-2.2.1.tar

what creates 

ESP8266_NONOS_SDK-2.2.1.tar.gz

**Comment by wilberforce** [comment]
This works:

curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp8266/ESP8266_NONOS_SDK-2.2.1.tar.gz| tar xfz - --no-same-owner

**Comment by MaBecker** [comment]
Thanks for your support and good night

**Comment by gfwilliams** [comment]
So do we think this is good to merge in now? It'll be nice to stop thrashing @tve's S3 account too :)

**Comment by MaBecker** [comment]
Good point, will move GCC to github too

**Comment by MaBecker** [comment]
I would say lets merge ;-)

**Comment by MaBecker** [comment]
Thank @gfwilliams

**Pull request merged**
