### PR TITLE
All server net.Socket are set to SO_REUSEADDR

### PR DESCRIPTION
**Pull request by opichals**
Same as in node.js https://nodejs.org/api/net.html#net_server_listen

### CODE REVIEW

**Comment by MaBecker** [comment]
wow, does this fix the socket problem?

**Comment by opichals** [comment]
It appears so. The --test-all works properly. At least on MacOS for me here.

**Comment by wilberforce** [comment]
Sorry - I'm missing something - where has `SO_REUSEADDR` been added to the code?

I see there is a new options parameter - do you need to set somehow with this?

**Comment by opichals** [comment]
ESP8266 doesn't have that option in its sdk I think.

**Comment by opichals** [comment]
Closing this in favor https://github.com/espruino/Espruino/pull/1527 with minimal changes.

**Pull request closed without merging**
