### PR TITLE
Esp32: Fix #1081 E.setBootCode();

### LINKED ISSUE #1081: E.setBootCode("")  let ESP32 reboot again and again
@gfwilliams
I try E.setBootCode("var a = 1") on ESP32 , after reboot , I get
Loading 18 bytes from flash...
Guru Meditation Error of type LoadProhibited occurred on core 0. Exception was unhandled.
Register dump:
PC : 0x400014fd PS : 0x00060f30 A0 : 0x80108476 A1 : 0x3ffd1840
A2 : 0x00100008 A3 : 0x00100004 A4 : 0x000000ff A5 : 0x0000ff00
A6 : 0x00ff0000 A7 : 0xff000000 A8 : 0x00000000 A9 : 0x3ffd17c0
A10 : 0x00000000 A11 : 0x40081be0 A12 : 0x00000004 A13 : 0x00000000
A14 : 0x00400000 A15 : 0x00000015 SAR : 0x0000000c EXCCAUSE: 0x0000001c
EXCVADDR: 0x00100008 LBEG : 0x400014fd LEND : 0x4000150d LCOUNT : 0xffffffff
Backtrace: 0x400014fd:0x3ffd1840 0x40108476:0x3ffd1850 0x401296ec:0x3ffd1870 0x40109f63:0x3ffd1890 0x4010a0db:0x3ffd18c0 0x4010a121:0x3ffd18e0 0x40132514:0x3ffd1900
Rebooting...

In the source code of Espruino-jsinteractive.c, I found that the js text code saved by E.setBootCode was loaded by jsfLoadjsfLoadStateFromFlash, not by jsfLoadBootCodeFromFlash, why?
Should the js text code saved by E.setBootCode be loaded by jsfLoadBootCodeFromFlash?

### PR DESCRIPTION
**Pull request by wilberforce**

### CODE REVIEW

**Comment by aifer2007** [comment]
great

**Comment by wilberforce** [comment]
@gfwilliams 

Are you happy for me to commit into master ESP32 changes which only affect the ESP32 code and not base espruino code?

This commit is ready to go.

**Comment by wilberforce** [comment]
@gfwilliams 

I've tried to modify to stop the conflicts, however did not succeed. Please can you sort these and pull this into master?

**Comment by wilberforce** [comment]
@gfwilliams 
Please can this be merged so that it is part of v1.92?

**Pull request merged**
