### PR TITLE
Fix advertising on nRF52840

### PR DESCRIPTION
**Pull request by urish**
Also refactored `advertising_init()`, `jsble_advertising_start()` to eliminate the duplicate call to `sd_ble_gap_adv_set_configure()`.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - but I'm a bit iffy about doing this with static vars. I know it seems dumb but when we're targeting nRF51 we have 6kB of RAM in total (including stack and JS), so having two of the `ble_advdata_t` (which are reasonably big) is going to hurt.

I've just committed some code that should fix this by removing `advertising_init` completely. Also found that setAdvertising didn't work on 52840 so have fixed that too.

**Comment by urish** [comment]
Actually, the static vars are only compiled in when targeting SDK >= 15, so I'm not sure if they are relevant for nRF51. But as long as advertising works on nRF52840 - I'm happy :)

**Comment by gfwilliams** [comment]
Ahh, I think it might have been a copy/paste issue then?

```
#if NRF_SD_BLE_API_VERSION<=5
    static ble_advdata_t advdata;
    static ble_advdata_t scanrsp;
#endif
```

Still static, just defined in a different place :) Anyway, as you say it should be working now - and the code is hopefully a bit simpler, which is always good.

**Comment by urish** [comment]
Yup, good spot - it was a copy-paste issue indeed. Always happy for simpler code!

**Comment by gfwilliams** [comment]
Just so you know, it seems that updating the advertising data causes the scan response to be cleared - so chances are we'll need a static array for the scan response eventually on SDK15 anyway (although I imagine that'll take the form of `m_enc_scan_response_data` to ensure that we're not recomputing everything all the time).

**Comment by gfwilliams** [comment]
But it's no big deal - right now it just means that when you update advertising it stops advertising the Nordic UART service

**Pull request closed without merging**
