### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by iotong**
1.fixed telnet recv function bug
2.addition shell function in linux system ,that allow excute shell cmd in espruino
3.addtion xtea crypto

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - why do you think `netRecv`is in error? As far as I can tell the data isn't zero-terminated so there's no problem using all 256 chars of the buffer.

Also you seem to have committed an extra bash script, and not added the `jswrap_mqtt` files? Out of interest, what did you find wrong with the existing JS MQTT implementation that you wanted a C based one for?

**Comment by iotong** [comment]
When I send a larger amount of data, telnet will lose a character, I did not carefully look for reasons. But when I changed 256 to 255, the problem was not happening, and I really wanted to use the mqtt protocol to rewrite it because I used the esp8266 module when using js mqtt when i could write the amount of code It will be much less, there is no transplant is completed, so there is no upload mqtt related code

**Comment by gfwilliams** [comment]
Hi - thanks for the changes, but you still haven't committed the missing files. For some reason `/libs/network/mqtt` is now in gitignore so you're not committing your jswrap files. If you check the 'travis' note next to your commit you can see that the changes you've sent don't compile: https://travis-ci.org/espruino/Espruino/builds/254742334

**Comment by MaBecker** [comment]
HI @iotong, 

does this fix issue #1037?

**Comment by gfwilliams** [comment]
Just to add, this is still broken because you haven't committed the files that are needed: https://travis-ci.org/espruino/Espruino/jobs/255994548

**Comment by MaBecker** [comment]
tried ca67ee6, works on my side.

```
>E.setBootCode()
Erasing Flash..................
Writing...
Compressed 25600 bytes to 8
Checking...
Done!
=undefined
>load();
=undefined
Loading 8 bytes from flash...
> 
```

@wilberforce  @jumjum123 this might work for ESP32 as well 

@gfwilliams added a fix for  #1037

**Comment by iotong** [comment]
@MaBecker yes ,it work!are you chinese?

**Comment by gfwilliams** [comment]
Please see: https://travis-ci.org/espruino/Espruino/jobs/256128299

Please can you commit `libs/network/mqtt/jswrap_mqtt.c` and `libs/network/mqtt/jswrap_mqtt.h`? Without this, I will have to close the PR as it doesn't build!

**Comment by iotong** [comment]
The transplant has not been completed, and I will restart the pull request after the completion of the transplant

**Comment by MaBecker** [comment]
@iotong I am german

**Comment by gfwilliams** [comment]
Great, thanks!

**Pull request closed without merging**
