### PR TITLE
Added docker-compose.yml for easier building of Espruino

### PR DESCRIPTION
**Pull request by ipepe**
Regarding #1689 I fixed building Espruino in Docker, also added docker-compose so it's much easier to build yourself an image.

### CODE REVIEW

**Comment by gfwilliams** [comment]
No reply...

**Comment by ipepe** [comment]
What reply was needed @gfwilliams ?

**Comment by gfwilliams** [comment]
I'd asked: `Does this line overwrite what was proviously specified in docker-compose.yml?` - you should see it above?

**Comment by ipepe** [comment]
That's how it looks on my side: Screenshot 2020-07-27 at 11 29 55

I'm not sure what do You mean with that question. Which line?

**Comment by gfwilliams** [comment]
Sorry - looks like that was my fault - I assumed review comments appeared automatically but it looks like it needed submitting...

This is what I had anyway...

image

So my concern was: Does it *always* build *ALL* boards now?

Also, looks like you removed the `RELEASE=1` line. The vast majority of builds for boards will fail without that in.

**Comment by ipepe** [comment]
> Sorry - looks like that was my fault - I assumed review comments appeared automatically but it looks like it needed submitting...
> 
> This is what I had anyway...
> 
> image
> 
> So my concern was: Does it _always_ build _ALL_ boards now?

Yes. But You can override it by env variable in `docker-compose.yml`

**Comment by gfwilliams** [comment]
Ok, great!

Looks like there are some merge conflicts now I'm afraid. Do you think you'd be able to help sort those out as I might break it doing so myself?

**Comment by ipepe** [comment]
I will take a look this week, I will refresh this PR and see what cloud be done better. Do You want me to make any specific changes?

**Comment by gfwilliams** [comment]
Thanks! I don't have any specific requests, no - it looks good

**Pull request closed without merging**
