### PR TITLE
Add custom TypeScript declarations in comments

### PR DESCRIPTION
**Pull request by qucchia**
You can now define custom types like this:
```c
/*TYPESCRIPT
type NRFFilters = {
  services?: string[];
  name?: string;
  namePrefix?: string;
  id?: string;
  serviceData?: object;
  manufacturerData?: object;
};
*/
```
And custom function types:
```js
{
  ...
  "typescript": [
    "declare function require<T extends keyof Libraries>(moduleName: T): Libraries[T];",
    "declare function require<T extends Exclude<string, keyof Libraries>>(moduleName: T): any;"
  ]
}
```
Finally you can also declare generic classes:
```js
{
  ...
  "typescript": "interface Array<T>"
}
```

### CODE REVIEW

**Comment by qucchia** [comment]
See the results here: https://github.com/qucchia/BangleApps/blob/typescript/typescript/types/main.d.ts

**Comment by qucchia** [comment]
Documented the build script so it hopefully isn't a completely incomprehensible mess.

**Comment by gfwilliams** [comment]
This looks great to me - fits in nicely without complicating things too much.

You think this is ready to merge?

**Comment by qucchia** [comment]
Yep!

**Pull request merged**
