### PR TITLE
fix jswrap_ESP8266_ping

### PR DESCRIPTION
**Pull request by MaBecker**
lost pingOpt.ip

### CODE REVIEW

**Comment by tve** [comment]
This line needs to be moved to the top, not just removed. I have a fix coming, but I'm testing a bunch of other stuff as well.

**Comment by MaBecker** [comment]
check the global at line 102

101  // Global data structure for ping request
102  static struct ping_option pingOpt;

**Comment by tve** [comment]
I mean: https://github.com/tve/Espruino/commit/c7cd61c59b1920880bc6686fe1bc22cf966149bc

**Comment by tve** [comment]
Redundant #874

**Pull request closed without merging**
