### PR TITLE
Use Dockerfile layers to cache dependency install

### PR DESCRIPTION
**Pull request by ikkala**
Before dependency install (provision.sh ALL), copy only required files.
Only after that, copy rest of the source code (COPY . /espruino) that
changes more often.
This way usually only lines starting from COPY . /espruino will
be executed.

### CODE REVIEW

**Comment by ikkala** [comment]
> Before dependency install (provision.sh ALL), copy only required files.

Note, you should review if the selected directories are enough / too much. I went through them by trial and error -- at least the whole build goes ok and I'm able to pull out zip fro Bangle.js.

**Comment by gfwilliams** [comment]
What's the reasoning for this? It just makes it faster by avoiding copying the `espruino` directory over? 

How much time does this save? I just tried here and it takes 2 seconds, so I'm not sure it warrants all the potential breakage that this might introduce?

**Comment by gfwilliams** [comment]
... or this actually allows provision.sh to not be called except right at the start?

**Comment by ikkala** [comment]
Each (almost) Dockerfile line creates new layered filesystem layer. The o[ld Dockerfile copies the source `COPY . /espruino` in very early step](https://github.com/espruino/Espruino/pull/1837/files#diff-3254677a7917c6c01f55212f86c57fbfL25) to a layer and after that the very long running dependency install and provision.sh steps are executed. Those long running steps takes some minutes to run, and what's worst is that they produce always multiple gigas of layer data to disk.

So, in development cycle where we change just one line of code and want to then build all that happen.  The new ordering of the Dockerfile tries to avoid this by moving the `COPY . /espruino` to the end so that docker build doesn't have to trigger the long running early steps at all.

**Comment by ikkala** [comment]
> I just tried here and it takes 2 seconds

Did you try docker build, after changing some source code?

**Comment by gfwilliams** [comment]
> Did you try docker build

Oh no, I mean I literally just tried the copy.

This sounds like a great idea then. I think the directories you've copied should be enough - do you actually need `espruino/targets` though? You may not...

**Comment by ikkala** [comment]
> do you actually need `espruino/targets` though? You may not...

Looks like it's fine without that, so I removed it now.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
