### PR TITLE
add variable COMPORT for easier flashing 

### PR DESCRIPTION
**Pull request by MaBecker**

### CODE REVIEW

**Comment by MaBecker** [comment]
hmm, travis failed for microbit and rak8211, i guess this is no issue.

**Comment by gfwilliams** [comment]
Please could you add `COMPORT?=/dev/ttyUSB0` to the Makefile? That way flashing will still work as it did before if no port is supplied

**Comment by MaBecker** [comment]
Sure, this way it is even simpler, because the two if's  can be removed - Thanks.

**Comment by gfwilliams** [comment]
Perfect - thanks!

**Pull request merged**
