### PR TITLE
add jshSPISendMany

### PR DESCRIPTION
**Pull request by atc1441**
only tx supported for now and no callback, Max 256 byte per request

this improves the sending of SPI data.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks, this looks good - do you think you'll be able to get RX and >256 byte done any time soon?

Personally I'm not sure I should merge this right now as it'll break SPI for anyone that's trying to receive data as well. You could always copy the 'weak' jshSPISendMany implementation from `jshardwarecommon.c` and then use that if there's an RX buffer or >256 bytes?

**Comment by atc1441** [comment]
The new changes should now enable RX and up to 4096 bytes on TX.

I also tested the Callback but that did brake the sending of the new byte because of the way it handles the sending. and the end of the sending.

**Comment by gfwilliams** [comment]
Looks great - thanks! Do you think you could just do

```
jshSPIWait(device);
if (callback) callback();
```

at the end?

That way even though sending in the background doesn't work, it doesn't matter. It'll just send in the foreground and call the callback when done? Then it doesn't break anything.

**Comment by atc1441** [comment]
Good idea

**Comment by gfwilliams** [comment]
Great! Are you happy that this is good to go? It looks fine to me. @MaBecker ?

**Comment by MaBecker** [comment]
Yes good to go, because it is  already in use locally with a generic **tft lcd unbuffered spi display driver** started in #1884.

**Pull request merged**
