### PR TITLE
Deepsleep for ESP32

### PR DESCRIPTION
**Pull request by jvvood**
Only timer based wakeup is working.

ESP32.deepsleep(time_in_milliseconds)

#1333

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great, thanks!

@jumjum123 @wilberforce are you guys happy with this? If so I'll merge.

**Comment by wilberforce** [comment]
@jrwood. Thanks for this.

There looks like there is a debug printf that could be removed.

@gfwilliams 
At this stage do we want to add a new esp32 deep sleep or should try to have a common `setDeepSleep`. I understand there are some esp8266 specific sleep functions too and the functionality is different....

**Comment by gfwilliams** [comment]
Yeah, it's difficult. The standard `setDeepSleep` for Espruino is totally different - it just enables a proper low power sleep mode where the device wakes up *with the entire contents of RAM still there* - STM32 has a different set of sleep modes to ESP8266. There's no timeout because it's all done automatically.

... so use of the whole `deepSleep` thing of the ESP8266/ESP32 is super confusing. Personally I'm happy with the current solution for the moment since the functionality is really pretty EspressIf-specific - but I'd bring it in-line with the ESP8266 one to avoid even more confusion:

* Change capitalisation so it's `deepSleep`
* Change milliseconds to microseconds (even though IMO milliseconds makes way more sense here)

**Comment by jvvood** [comment]
@gfwilliams
I've changed them according to your suggestions.

**Comment by gfwilliams** [comment]
Great - thanks for doing those changes so quickly - merging!

**Pull request merged**
