### PR TITLE
allow  1MB

### PR DESCRIPTION
**Pull request by MaBecker**
without FOTA 1MB boards can now use the complete 1MB flash

FLASH_1MB=1 NO_FOTA=1  make

### CODE REVIEW

**Comment by MaBecker** [comment]
please do not merge now

**Comment by MaBecker** [comment]
good to go :)

**Comment by gfwilliams** [comment]
Nice - thanks! This looks much tidier

**Comment by MaBecker** [comment]
ok , done with test - ready to merge.

**Pull request merged**
