### PR TITLE
strip file names and line numbers from tensorflow error messages for release build

### PR DESCRIPTION
**Pull request by fanoush**
- add gcc option to strip build folder absolute path from __FILE__ macro
- make tensorflow NDEBUG dependent on RELEASE - may enable more debug stuff for non-release builds
- disable logging lines and source file names based on NDEBUG

### CODE REVIEW

**Comment by fanoush** [comment]
can you check if you like this? the tensorflow patch file for patching original source is not there yet, will generate it if changes are OK

**Comment by gfwilliams** [comment]
Thanks! Looks good to me... Did you spot if not having `-DNDEBUG` included anything specific? It seems odd I'd included it all the time before (I might have done it just so that I could build *something* :) )

**Comment by fanoush** [comment]
NDEBUG should disable asserts and some profiler code, see https://github.com/espruino/Espruino/search?q=NDEBUG&type=code
I actually did not try to **run** non-release build in the device to see what those asserts do now but it builds and links fine in both cases. If you do run such builds maybe you'll decide to put it back later?

I have added patch produced by `git diff`. It looks normal, same unified diff style as the 01 one, just the first line says `diff --git` so  I hope it is fine.

**Comment by gfwilliams** [comment]
Ok, thanks! This looks great! I think the first line of the diff usually gets ignored anyway.

**Pull request merged**
