### PR TITLE
ESP32  jshGetSystemTime() make interrupt tolerant

### PR DESCRIPTION
**Pull request by wilberforce**
Pull @jumjum123 changes from ESP32 branch into master

### CODE REVIEW

**Comment by opichals** [comment]
Perhaps there should be an initializer like this instead of just undefined content?
```
   portMUX_TYPE mux = portMUX_INITIALIZER_UNLOCKED;
```

Adding an interesting article link about the ESP32 synchronization stuff https://techtutorialsx.com/2017/09/30/esp32-arduino-external-interrupts/

**Comment by gfwilliams** [comment]
Just added that for you.

**Comment by wilberforce** [comment]
@gfwilliams 

Thanks Gordon - that was unexpected!

**Comment by gfwilliams** [comment]
Just saves everyone some time if it's a one-liner :)

**Pull request merged**
