### PR TITLE
update ESP32 Branch to UDP, copy UDP code from linux

### PR DESCRIPTION
**Pull request by wilberforce**
@gfwilliams 

Not yet ready to merge..

@opichals - I have updated the ESP32 network code. Please can you review?

`WARNING: setsockopt(SO_REUSPORT) failed`

This occured all the time so I commented out.

It looks like  `test_dgram_socket.js` is failing, as I get:

```
=undefined
server disconnected
client disconnected
```

Extending the timeout to 10 secs, I could then dump this.

```
>srv
=dgramSocket { "type": 2,
  "opt": {  },
  "conn": false,
  "#onbind": function (bsrv) { ... },
  "port": 41234, "sckt": 3,
  "#onclose": function () { ... },
  "#onmessage": function (msg,info) { ... }
 }
>client
=dgramSocket { "type": 2,
  "opt": {  },
  "sckt": 4, "conn": true,
  "#onmessage": function (msg,info) { ... },
  "#onclose": function () { ... },
  "dSnd": ""
 }
server disconnected
client disconnected
```

### CODE REVIEW

**Comment by wilberforce** [comment]
Linux output:
```
=undefined
<"42"
<{"address":"127.0.0.1","port":57224,"size":2}
>"42!"
>{"address":"127.0.0.1","port":41234,"size":3}
server disconnected
client disconnected
```

**Comment by opichals** [comment]
The changes look ok to me. Perhaps you could compile with NET_DBG > 0 and send the output?

**Comment by wilberforce** [comment]
@opichals 
Thanks. With NET_DBG:

```
>
=undefined
Send 2 100007f:41234server disconnected
client disconnected
> 
```

**Comment by opichals** [comment]
Looks like there is something not working on the 'recv' end.

**Comment by wilberforce** [comment]
@opichals 

> Looks like there is something not working on the 'recv' end.

Buy doing the send with linux and recv with ESP32 I can confirm that the ESP32 recevies ok.

It is the send that is not working - the client side.

**Comment by wilberforce** [comment]
image

**Comment by opichals** [comment]
Cool! @wilberforce Thank you, it would have taken much longer to figure out for me.

**Comment by wilberforce** [comment]
@opichals 

> Cool! @wilberforce Thank you, it would have taken much longer to figure out for me.

It works in the independant case. Your intial sample of both client and server with the same script seems does not work on the client send - so I'm not sure what is up with that.

**Comment by wilberforce** [comment]
@gfwilliams 

Please merge

**Comment by gfwilliams** [comment]
Ok, thanks!

**Pull request merged**
