### PR TITLE
Upload GitHub Build Artifacts

### PR DESCRIPTION
**Pull request by DanTheMan827**
Since you already had an action, I modified it to also upload the build artifacts as well.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Where does it upload them to/how do you get them?

Because they are already all uploaded to https://www.espruino.com/binaries/travis/ /  https://www.espruino.com/binaries/travis/master

**Comment by DanTheMan827** [comment]
@gfwilliams it attaches them to the github action run.

Example from my fork: https://github.com/DanTheMan827/Espruino/actions/runs/2849321887

You don't have to if you don't want, but I figured it's just another source for them

**Comment by gfwilliams** [comment]
Great - thanks! Yes, that looks neat.

Maybe I'll have to re-evaluate if GitHub starts charging for storage somehow, but until then this seems like a neat thing to have. Also for anyone wanting to clone, make a change and have it built for them

**Comment by DanTheMan827** [comment]
@gfwilliams you may want to change the action to run on all branches along with a check for `ci_upload.sh` to only run when on master.

Ideally, someone forking to make changes would also make a branch for those changes rather than work on their master, and the action wouldn't run for them.

**Pull request merged**
