### PR TITLE
Identify libraries and optional arguments in JSON

### PR DESCRIPTION
**Pull request by qucchia**
For the TypeScript typing I have to know which classes are libraries (which must be retrieved using `require()`) and which are global variables. Hopefully this shouldn't break Tern?

### CODE REVIEW

**Comment by qucchia** [comment]
This last commit also adds a question mark to arguments that are explicitly described as optional (their documentation beginning with `[optional]`).

**Comment by gfwilliams** [comment]
Thanks - have you been able to test the generated file with tern?

The other option is just to copy `scripts/build_tern_json.js` and instead use it to output typescript decls directly? Then you have access to a lot more info (for instance if needed we could add extra fields to the JSON which you could then access)

**Comment by qucchia** [comment]
Oh true! That would be neater. Perhaps it would be cool to put the types in their own dedicated NPM package?

**Comment by gfwilliams** [comment]
> Perhaps it would be cool to put the types in their own dedicated NPM package?

Not sure I understand - you mean the generated types, rather than the type info that's currently sitting in JSON?

**Comment by qucchia** [comment]
Yeah - something like this: https://www.npmjs.com/package/@types/espruino. If not it doesn't matter though.

**Pull request closed without merging**
