### PR TITLE
add squared bezier curve

### PR DESCRIPTION
**Pull request by MaBecker**
as discussed in `New vector font #1721`

### CODE REVIEW

**Comment by MaBecker** [comment]
Not sure any more if this is really needed.....

**Comment by MaBecker** [comment]
Not sure any more if this is really needed.....

**Comment by gfwilliams** [comment]
I don't know - seems like a good utility function to have available. Could be useful for other stuff (like stepper motor control) too.

Although maybe in most cases it'd be fine to have the JS version. Anyone else have any thoughts?

**Comment by MaBecker** [comment]
It's not lost, it will return at leased as  JS module ;-)

But for now it's just needed as a helper for creating fonts.

[quadraticBezier.c.txt](https://github.com/espruino/Espruino/files/4072516/quadraticBezier.c.txt)

**Pull request closed without merging**
