### PR TITLE
Esp32 neopixel debug

### PR DESCRIPTION
**Pull request by ExCyb**
Hi! Here is some fixes to esp32 neopixel from SergeP. Improved slightly from forum version to be more readable.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Forum post about this here: http://forum.espruino.com/conversations/330748/#comment14644546

**Comment by gfwilliams** [comment]
@MaBecker should I merge this? You seem to do quite a bit of neopixel stuff, so does it improve life for you?

**Comment by MaBecker** [comment]
Well the existing Neopixel implementation is working as expected.  

>  so does it improve life for you?

NO

**Comment by gfwilliams** [comment]
Ok, thanks! Actually looking at the code again and at http://forum.espruino.com/conversations/330748/#comment14644546 it looks entirely likely that the existing ESP32 code had issues with longer strings of neopixels (also this code is a bit tidier than before) so merging anyway.

**Comment by MaBecker** [comment]
Did some tests with up to 300 pixel,  still works as expected :)

**Pull request merged**
