### PR TITLE
Update E_showScroller.js

### LINKED ISSUE #2153: Bangle 1: E.showScroller() triangle drawn over top item
Using the sample [E.showscroller code from the documentation](http://www.espruino.com/Reference#l_E_showScroller), when run on the Bangle.js 1 emulator the top triangle is drawn over the list items.

When I originally posted about this, Gordon suggested it was intended to work with widgets. It does look better with widgets enabled, but that would mean the triangle overdraws the widgets instead?

### PR DESCRIPTION
**Pull request by andrewgoz**
Respect Bangle.appRect
Only draw arrows when needed
Prefer to draw selection in middle of screen
Implement scroll function
Pass selected flag to draw function
Make selection box drawing optional
Fixes #2153

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - although it looks like `scroll` is now a function? If you assigned that through then I don't think it'd work

**Comment by andrewgoz** [comment]
For some reason my head said scroll needed to be a function. It's now back to being a property.

**Comment by gfwilliams** [comment]
Thanks! You think this is ready for merging?

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
