### PR TITLE
Workaround for building on gcc versions > 6.

### PR DESCRIPTION
**Pull request by swineone**

### CODE REVIEW

**Comment by MaBecker** [comment]
Hi, @swineone,
what is the benefit of using a higher gcc version?

**Comment by swineone** [comment]
> Hi, @swineone,
> what is the benefit of using a higher gcc version?

No idea, really. I'm just used to updating when new versions coming out -- I assume optimizations are better, etc.

Hopefully this doesn't dissuade anyone from merging this fix, as it's as simple and harmless as it gets.

**Comment by gfwilliams** [comment]
Thanks for this - newer GCCs do sometimes get better code density and speed, but I've had issues with some (sometimes the manufacturer-provided HALs do non-compliant stuff and end up getting broken) so I don't tend to change compiler unless there's a good reason.

Do you have any background as to why swapping the order of object files around actually helps? What error does it fix? It just seems like something that shouldn't really have any effect at all?

**Comment by gfwilliams** [comment]
Aha - I just spotted your forum post - thanks! Loads of info there :)

http://forum.espruino.com/conversations/331066/#comment14658810

**Pull request merged**
