### PR TITLE
ESP32 improvements

### PR DESCRIPTION
**Pull request by MaBecker**
- add FLASH_BAUD
- fix erase_flash
- switch jsWarn()  to jsDevInfo()
- keep jsWarn()/ jsError() for not implemented functions
- switch jsError() to jsExceptionHere() if helpfull

### CODE REVIEW

**Comment by MaBecker** [comment]
#1880

**Comment by gfwilliams** [comment]
Thanks - looks great!

However with `bluetooth.c`, don't we actually want to keep the warnings, or some kind of print that appears for normal release users? It feels quite important to tell them that a function isn't implemented - potentially it should even be an exception.

**Comment by MaBecker** [comment]
Thanks, yes keep jsWarn() for BLE and just add jsExceptionHere() where useful.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
