### PR TITLE
Add Makefile to easy esptool-based flashing

### PR DESCRIPTION
**Pull request by opichals**
Try `make help` to see available targets and their descriptions.

### CODE REVIEW

**Comment by MaBecker** [comment]
Do you know that Makefile for ESP have some flash options?

**Comment by MaBecker** [comment]
Most of them download a ready to go firmware and then they struggle because they bought cheap boards with slow flash modes.

**Comment by MaBecker** [comment]
What about maintain the page and the Readme file too.

https://github.com/espruino/EspruinoDocs/blob/master/tutorials/ESP8266_Flashing.md

https://github.com/espruino/Espruino/blob/master/targets/esp8266/README_flash.txt

**Comment by gfwilliams** [comment]
Thanks! Would it be possible to change the location of the Makefile though? And update https://github.com/espruino/Espruino/blob/master/targets/esp8266/README_flash.txt ? All the other boards have the makefiles in the `make` directory - for example:

* nRF52 flashing : https://github.com/espruino/Espruino/blob/master/make/common/NRF5X.make#L461
* STM32 flashing: https://github.com/espruino/Espruino/blob/master/make/common/STM32.make#L38

**Comment by opichals** [comment]
The intention of my addition was that the release .zip files would contain [the Makefile](https://github.com/espruino/Espruino/pull/1772/files#diff-382db1665e3e7df44f93aec61c63bf8aR104) for people (me ;)) to avoid constructing the `esptool` command line arguments over and over when a firmware update is due. The `common/XYZ.make` files are not distributed along IIRC. There is already [ESP8266 flashing present in the makefiles](https://github.com/espruino/Espruino/blob/master/make/targets/ESP8266.make#L147).

The Makefile It is basically a copy of the README_flash.txt but for some people that still can be a valid source of information (those not using `make`) so I am not sure on that one.

**Comment by gfwilliams** [comment]
Ahh, sorry - that makes way more sense. Thanks!

**Comment by MaBecker** [comment]
@opichals Ok - got it.

**Pull request merged**
