### PR TITLE
print big numbers

### PR DESCRIPTION
**Pull request by jbgagnon**
take only  src/jsutils.c
it is only for big numbers.
not small numbers because small numbers are round near integer so small number are always round to zero ...

this is for #1489

sorry for the delay

### CODE REVIEW

**Comment by jbgagnon** [comment]
Is there any big endian module ?
Because, I have to make some changes if big endian is supported
(just a line two change if someone give me the good #ifdef )

**Comment by gfwilliams** [comment]
Thanks for removing the other files. If you're distributing your builds to others, the removal of the "maybe donate something" text is a bit unreasonable though.

Is it possible to do a simpler version without the bitwise math? It's cool, but if Espruino were on big endian systems it'd be an annoying bug.

Also on some of these boards (ESP8266 512k, some of the ARM boards) I'm really struggling with flash memory usage, and I feel like reimplementing pow10 and doing bit hacks rather than just doing `log` and `jswrap_math_pow(10,...)` is just increasing the code side when I imagine if you're converting massive double numbers into strings it's kindof unlikely that speed is of the essence?

**Comment by jbgagnon** [comment]
for big endian it's just a line replacing
       int p2 = (((unsigned short *)& val)[3] << 1 >> 5) - 0x3ff;
by
       int p2 = (((unsigned short *)& val)[0] << 1 >> 5) - 0x3ff;
(I think)
but it need to be tested

you can also use my pow10int function for replacing at line 549 comment

for testing 
for(var i=0,j=1;i<=308;i++) { console.log(i, j); j *=10; }
for(var i=0,j=10;i<=308;i++) { console.log(i, j/7); j *=10; }
is a start

**Comment by jbgagnon** [comment]
sorry for the "donate ..." it's all what  I find to make difference from my version of the original  one.
Certainly stupid 
and I discovering git and comminting bad  things ...

**Comment by gfwilliams** [comment]
Sorry for the delay - closing this finally - just pulled this in manually with some changes to handle small numbers too

**Pull request closed without merging**
