### PR TITLE
Nucleo l476 rg analog

### PR DESCRIPTION
**Pull request by VVESTM**
Hello Gordon,

Here are some updates for Nucleo L476 RG board.
It adds adc and dac functionnalities.

Regards
Vincent

### CODE REVIEW

**Comment by gfwilliams** [comment]
Cool - thanks!

**Comment by VVESTM** [comment]
Thanks Gordon
With this pull request, the SW concerning stm32 low layer api on NucleoL476RG is pretty complete.

Vincent

**Comment by gfwilliams** [comment]
Wow, thanks! How portable do you think this is to different parts?

There's a post on the forum at the moment where someone is trying to port to the Nucleo F413:

http://forum.espruino.com/conversations/299344/#comment13447980

**Comment by VVESTM** [comment]
Low Layer API are done to ease the portage on differents chips. It will be portable if there is no big difference on the IP used.
Unfortunately, this is not yet available on all the platforms. The first family to benefit of this API was L4. It will come for F4 during first or second quarter. So need to wait a little bit more for F413...
Once the LL is available on F4, it should be straight forward to run my software on this board.

**Pull request merged**
