### PR TITLE
W600 porting

### PR DESCRIPTION
**Pull request by beanjs**
* Feature

- [x] GPIO
- [x] UART
- [x] SPI
- [x] I2C
- [x] wifi
- [x] netwotk
- [x] test

### CODE REVIEW

**Comment by beanjs** [comment]
I have a request, can I join the espruino project?

**Comment by beanjs** [comment]
@nkolban w600 porting details

**Comment by beanjs** [comment]
@MaBecker

**Comment by MaBecker** [comment]
@beanjs can W600 do i2c master and slave?

**Comment by beanjs** [comment]
in my port，only support master。but sdk can do master and slave

**Comment by beanjs** [comment]
porting complete, please merge it.

**Comment by beanjs** [comment]
w600 build environment on Docker:https://github.com/beanjs-framework/dev-env

**Comment by gfwilliams** [comment]
Wow, that was impressively fast! This looks great!

I don't believe creating a new jshConsoleSetup function is needed though - if jshIsDeviceInitialised, jshUSARTSetup should get called automatically I believe... At least it works on all other platforms.

I'll merge this into UNMAINTAINED_BOARDS for the moment and see what happens - it's great that you've done this but I don't get funding for any of the work on Espruino, and I can't afford to work for free to ensure that every time I make a change all the builds for new boards keep building.

**Comment by gfwilliams** [comment]
Ok, now merged and part of https://github.com/espruino/Espruino/tree/UNMAINTAINED_BOARDS/targets/w600

thanks!

**Pull request closed without merging**
