### PR TITLE
change toggle function

### PR DESCRIPTION
**Pull request by lancernet**
change toggle function to return after toggle pin state

### CODE REVIEW

**Comment by gfwilliams** [comment]
I'm afraid I can't merge this... This change should require changing maybe 3 lines, but this PR changes 18 files!

Also your solution doesn't work I'm afraid - since it reads the input rather than the state of the output (which was stored in the 'on' variable anyway).

I've just committed something that will add this functionality thugh

**Comment by lancernet** [comment]
Sorry, i just learned to use github. I am sorry to bring you inconvenience

**Comment by gfwilliams** [comment]
No problem :) It is a good idea to return the value.

When you add your code to GitHub you can often click to  'compare' it and see what has changed - you can then tell if you've changed what you expected to change as it is easy to commit things by accident :)

**Comment by lancernet** [comment]
thanks you gfwilliams

**Comment by wilberforce** [comment]
@gfwilliams 

https://github.com/espruino/Espruino/blob/267fc7bc61df9db1956dc361bd03da8dce408c28/src/jswrap_pin.c#L185

If the pin in invalid nothing is returned and the compiler complains. Can we return a javascript undefined with a return type of bool?

**Comment by gfwilliams** [comment]
Just fixed. No, we can't - I've switched it to return false.

It's super unlikely anyway, since you'd have to do something like `Pin.toggle.call(undefined)` - in which case you get what you deserve really :)

**Pull request closed without merging**
