### PR TITLE
remove getBuildHash and add mqtt library

### PR DESCRIPTION
**Pull request by iotong**
remove getBuildHash and add mqtt library

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks for this - but just wondering:

* Why was getBuildHash removed? It was added for a good reason - any code saved with 'save()' in an older version of Espruino won't work
* Why do you want to build mqtt in? What is wrong with the JS version of it that can't be fixed by changing the JS? Many Espruino boards just dont have the available flash to have this built in all the time.

**Comment by iotong** [comment]
1. The old version of the code can't run because the native function reference has an error. So just modify the pointer to the native function to solve the problem! 2. Create native mqtt because it will consume less variable

**Comment by gfwilliams** [comment]
If the JS code does something like `a=print; setInterval('print("Hello")',100)` then your changes will just make the board crash as soon as it loads the code. I don't think that's an improvement.

I can see you might want to add a parameter to `load()` to *force* it to load saved code from an older version, but just making the board load by default is a bad idea.

Sorry, but I'm not willing to merge this - you could just add `JSMODULESOURCES += libs/js/mqtt.min.js` to the `BUILD.py` file and include the JS which will instantly save loads of variables. Even if your library would fit on all the Espruino boards (which it won't at the moment), it appears to have at least one memory leak when saving, the API is subtly different to the existing MQTT library, and the code doesn't appear to be able to cope with MQTT commands that are spread across multiple network packets, which the JS version does - it would just end up being a complete pain to maintain.

**Comment by gfwilliams** [comment]
If the JS code does something like `a=print; setInterval('print("Hello")',100)` then your changes will just make the board crash as soon as it loads the code. I don't think that's an improvement.

I can see you might want to add a parameter to `load()` to *force* it to load saved code from an older version, but just making the board load by default is a bad idea.

Sorry, but I'm not willing to merge this - you could just add `JSMODULESOURCES += libs/js/mqtt.min.js` to the `BUILD.py` file and include the JS which will instantly save loads of variables. Even if your library would fit on all the Espruino boards (which it won't at the moment), it appears to have at least one memory leak when saving, the API is subtly different to the existing MQTT library, and the code doesn't appear to be able to cope with MQTT commands that are spread across multiple network packets, which the JS version does - it would just end up being a complete pain to maintain.

**Comment by gfwilliams** [comment]
If the JS code does something like `a=print; setInterval('print("Hello")',100)` then your changes will just make the board crash as soon as it loads the code. I don't think that's an improvement.

I can see you might want to add a parameter to `load()` to *force* it to load saved code from an older version, but just making the board load by default is a bad idea.

Sorry, but I'm not willing to merge this - you could just add `JSMODULESOURCES += libs/js/mqtt.min.js` to the `BUILD.py` file and include the JS which will instantly save loads of variables. Even if your library would fit on all the Espruino boards (which it won't at the moment), it appears to have at least one memory leak when saving, the API is subtly different to the existing MQTT library, and the code doesn't appear to be able to cope with MQTT commands that are spread across multiple network packets, which the JS version does - it would just end up being a complete pain to maintain.

**Pull request closed without merging**
