### PR TITLE
Timer updates, update to esp-idf 2.1, 10 sockets

### PR DESCRIPTION
**Pull request by wilberforce**

### CODE REVIEW

**Comment by wilberforce** [comment]
@gfwilliams 

The travis build seems to be failing for BOARDS with which the code in this pull does not alter?

This is now building for the ESP32 - updated to esp-idf 2.1 and @jumjum123 's timer updates

```
>process.env
={
  "VERSION": "1v93.167",
  "BUILD_DATE": "Aug 14 2017",
  "BUILD_TIME": "20:43:09",
  "GIT_COMMIT": "c5efaf6c3086d2993d099c281b8bfbd802dcb734",
  "BOARD": "ESP32",
  "CHIP": "ESP32",
  "CHIP_FAMILY": "ESP32",
  "FLASH": 0, "RAM": 524288,
  "SERIAL": "240ac400-2f90",
  "CONSOLE": "Telnet",
  "EXPORTS": { "jsvLock": 1074615584, "jsvLockAgainSafe": 1074615728, "jsvUnLock": 1074618344, "jsvSkipName": 1074635984,
    "jsvMathsOp": 1074646088, "jsvMathsOpSkipNames": 1074648596, "jsvNewFromFloat": 1074631720, "jsvNewFromInteger": 1074631632, "jsvNewFromString": 1074630248,
    "jsvNewFromBool": 1074631692, "jsvGetFloat": 1074640592, "jsvGetInteger": 1074634268, "jsvGetBool": 1074641172, "jspeiFindInScopes": 1074660404,
    "jspReplaceWith": 1074660136, "jspeFunctionCall": 1074670468, "jspGetNamedVariable": 1074661904, "jspGetNamedField": 1074662292, "jspGetVarNamedField": 1074662408,
    "jsvNewWithFlags": 1074629828 }
 }
>ESP32.getState()
={
  "sdkVersion": "v2.1",
  "freeHeap": 129720, "addr": 65536,
  "partitionBoot": "factory"
 }
> 
```

**Comment by gfwilliams** [comment]
I wouldn't worry about those two. The MICROBIT fail is my fault, and the RUUVITAG one just seems to be a failure in the travis system, not your code.

**Comment by gfwilliams** [comment]
Do you think this is ready to merge then?

**Comment by wilberforce** [comment]
@gfwilliams

Yes - ready to merge

**Comment by gfwilliams** [comment]
Great, thanks!

**Pull request merged**
